### ISSUE TITLE
Using Signature.Core doesn't update InternalsVisibleTo fields for DLLs which are not present.

### ISSUE THREAD

**Issue by gravufo** [MyGet/webhooks-sign-package#4]
I am trying to strong-name sign the [Akka NuGet package](https://www.nuget.org/packages/Akka).
Signing is complete, but it doesn't seem to update the InternalsVisibleTo fields which leads to the following error:
`Unhandled Exception: System.MethodAccessException: [D:\AkkaTest\Akka test\Akka test\bin\Debug\Akka.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.`

Is there something I'm doing wrong?

Thanks

**Comment by xavierdecoster** [comment]
You need to sign both assemblies and put the public key in the InternalsVisibleTo attribute. See http://stackoverflow.com/questions/1123683/how-to-declare-a-friend-assembly.

**Comment by gravufo** [comment]
I can't do that. I'm trying to sign a NuGet package using Signature.Core.
When getting the Akka NuGet package, only one DLL is provided (Akka.dll) and your tool will sign that .nupkg by extracting, signing and rezipping. The InternalsVisibleTo were not declared by me, but by Akka in their DLL.

One example is that they have a InternalsVisibleTo Akka.Remote which is part of another NuGet package. These fields don't get updated, so the NuGet package is signed, but won't work.

How would I go about signing Akka NuGet packages then?

Thanks

**Comment by maartenba** [comment]
Please reach out to the authors of Signature.Core (https://www.nuget.org/packages/Signature.Core), we provide this sample as a demonstration of our web hooks.

**Comment by gravufo** [comment]
Okay, thanks!
